apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /Users/mwilkerson/dev/rollouts-plugin-trafficrouter-consul
        containerPath: /rollouts-plugin-trafficrouter-consul