# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: static-server
spec:
  selector:
    app: static-server
  ports:
    - name: http
      port: 80
      targetPort: 8080