controller:
  image:
    # -- Registry to use
    registry: quay.io
    # -- Repository to use
    repository: argoproj/argo-rollouts
    # -- Overrides the image tag (default is the chart appVersion)
    tag: ""
    # -- Image pull policy
    pullPolicy: IfNotPresent
  trafficRouterPlugins:
    - name: "hashicorp/consul"
      location: "file:///plugin-bin/hashicorp/rollouts-plugin-trafficrouter-consul"
  volumes:
    - name: consul-route-plugin
      hostPath:
        path: /rollouts-plugin-trafficrouter-consul
        type: DirectoryOrCreate
  volumeMounts:
      - name: consul-route-plugin
        mountPath: /plugin-bin/hashicorp