# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rollouts-plugin-trafficrouter-consul
rules:
  - verbs:
      - create
      - watch
      - get
      - update
      - patch
    apiGroups:
      - consul.hashicorp.com
    resources:
      - servicesplitters
      - serviceresolvers
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rollouts-plugin-trafficrouter-consul
  labels:
    app.kubernetes.io/component: rollouts-controller
    app.kubernetes.io/name: argo-rollouts
    app.kubernetes.io/part-of: argo-rollouts
subjects:
  - kind: ServiceAccount
    name: argo-rollouts
    namespace: argo-rollouts
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rollouts-plugin-trafficrouter-consul